export default [
  {
    id: 1,
    name: "Project 1",
    description: "My first project",
    createdAt: "10 days ago",
  },
  {
    id: 2,
    name: "Project 2",
    description: "My second project",
    createdAt: "25 days ago",
  },
  {
    id: 3,
    name: "Project 3",
    description: "My third project",
    createdAt: "10 days ago",
  },
  {
    id: 4,
    name: "Project 4",
    description: "My first project",
    createdAt: "10 days ago",
  },
  {
    id: 5,
    name: "Project 5",
    description: "My second project",
    createdAt: "25 days ago",
  },
  {
    id: 6,
    name: "Project 6",
    description: "My third project",
    createdAt: "10 days ago",
  },
  {
    id: 7,
    name: "Project 7",
    description: "My first project",
    createdAt: "10 days ago",
  },
  {
    id: 8,
    name: "Project 8",
    description: "My second project",
    createdAt: "25 days ago",
  },
  {
    id: 9,
    name: "Project 9",
    description: "My third project",
    createdAt: "10 days ago",
  },
  {
    id: 10,
    name: "Project 10",
    description: "My first project",
    createdAt: "10 days ago",
  },
  {
    id: 11,
    name: "Project 11",
    description: "My second project",
    createdAt: "25 days ago",
  },
  {
    id: 12,
    name: "Project 12",
    description: "My third project",
    createdAt: "10 days ago",
  },
  {
    id: 13,
    name: "Project 13",
    description: "My first project",
    createdAt: "10 days ago",
  },
  {
    id: 14,
    name: "Project 14",
    description: "My second project",
    createdAt: "25 days ago",
  },
  {
    id: 15,
    name: "Project 15",
    description: "My third project",
    createdAt: "10 days ago",
  },
];
